bungalapak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_item, delete_item, add_item_ajax, create_mood_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-item/<uuid:id>', edit_item, name='edit_item'),
    path('delete/<uuid:id>', delete_item, name='delete_item'),
    path('create-item-ajax', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_mood_flutter, name='create_mood_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %} {% endblock meta %}
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<style>
    /* Tambahan CSS untuk navbar yang berubah warna */
    .navbar-scrolled {
        background-color: #b66878;
        transition: background-color 0.5s ease, color 0.5s ease;
    }
    .navbar-scrolled h1,
    .navbar-scrolled a {
        color: white !important; /* Warna teks berubah menjadi putih */
        transition: color 0.5s ease
    }
    .navbar-scrolled span {
        color: #ffd198 !important;
        transition: color 0.5s ease
    }
    /* Aturan CSS untuk hover pada navbar yang sudah discroll */
    .navbar-scrolled a:hover {
        background-color: #a05464 !important; /* Mengubah background ketika di-hover */
        transition: background-color 0.5s ease; /* Memperlancar transisi background */
    }

    .navbar-scrolled .mobile-menu a:hover {
        background-color: #a05464 !important; /* Konsistensi hover di mobile menu */
    }
</style>

<!-- Navbar -->
<nav class="navbar bg-white fixed top-0 left-0 z-40 w-screen">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <h1 class="text-2xl font-bold text-center text-[#b66878]">Bungalapak</h1>
            </div>
            <div class="hidden md:flex items-center space-x-4 font-bold">
                    <a href="{% url 'main:show_main' %}" class="text-[#b66878] hover:bg-gray-300 py-2 px-4 rounded transition duration-300">
                        Home
                    </a>
                    <a href="{% url 'main:show_main' %}#products" class="text-[#b66878] hover:bg-gray-300 py-2 px-4 rounded transition duration-300">
                        Products
                    </a>
                    <a href="{% url 'main:show_main' %}#contacts" class="text-[#b66878] hover:bg-gray-300 py-2 px-4 rounded transition duration-300">
                        Contacts
                    </a>
                {% if user.is_authenticated %}
                    <span class="text-[#FAA943] mr-4">Welcome, {{ user.username }}</span>
                    <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                        Logout
                    </a>
                {% else %}
                    <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
                        Login
                    </a>
                    <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                        Register
                    </a>
                {% endif %}
            </div>
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button">
                    <svg class="w-6 h-6 text-[#b66878]" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                        <path d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full">
        <div class="pt-2 pb-3 space-y-1 mx-auto font-bold">
                <a href="{% url 'main:show_main' %}" class="block text-[#b66878] hover:bg-[#a05464] py-2 px-4 rounded transition duration-300">
                    Home
                </a>
                <a href="{% url 'main:show_main' %}#products" class="block text-[#b66878] hover:bg-[#a05464] py-2 px-4 rounded transition duration-300">
                    Products
                </a> 
                <a href="{% url 'main:show_main' %}#contacts" class="block text-[#b66878] hover:bg-[#a05464] py-2 px-4 rounded transition duration-300">
                    Contacts
                </a>
            {% if user.is_authenticated %}
                <span class="block text-[#FAA943] px-3 py-2">Welcome, {{ user.username }}</span>
                <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                    Logout
                </a>
            {% else %}
                <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
                    Login
                </a>
                <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                    Register
                </a>
            {% endif %}
        </div>
    </div>
    <script>
        const btn = document.querySelector("button.mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");
      
        btn.addEventListener("click", () => {
          menu.classList.toggle("hidden");
        });

        // Navbar scroll change
        window.addEventListener("scroll", function() {
            const navbar = document.querySelector("nav");
            if (window.scrollY > 100) {
                navbar.classList.add("navbar-scrolled");
            } else {
                navbar.classList.remove("navbar-scrolled");
            }
        });
      </script>
</nav>